### ISSUE TITLE
Invalid server info

### ISSUE THREAD

**Issue by dos65** [pycontribs/jira#114]
Hi, i tried to work with JIRA v4.2.4 and api v2.0.alpha1 and got error on server_info processing.
This version returns info without `versionNumbers` field.
https://github.com/pycontribs/jira/blob/master/jira/client.py#L263

**Comment by ssbarnea** [comment]
Can you provide the entire response you get from the server? Unless we find a fallback method for the version detection I may have to document that very old versions of JIRA are not supported anymore. 

Because of API changes, I do need to detect JIRA version before starting to do things with it. Anyway, the code could be changed to throw an error on the log and to assume a jira version of 4.2.0 or so.

**Comment by dos65** [comment]
Here is serverInfo response from these jira version:
```
{
  "baseUrl": "***",
  "version":"4.2.4b-591",
  "buildNumber":591,
  "buildDate":"2011-02-02T00:00:00.000+0300",
  "serverTime":"2015-08-06T14:18:02.585+0300",
  "scmInfo":"",
  "serverTitle":"*** task/bug tracker"
}
```

**Comment by ssbarnea** [comment]
This looks like a beta JIRA version and clearly I will not be able to support ancient versions. If you make pull requests I will probably accept them, if they do not break current versions.
