### ISSUE TITLE
Unable to download any large binary attachments due to pathologically slow character encoding checks being invoked for binary responses

### ISSUE THREAD

**Issue by coddingtonbear** [pycontribs/jira#115]
In the `requests` library the use of `.text` causes the character encoding of the document being retrieved to be either inferred from the response's `Content-Type` headers, or from the content of the response itself if the `Content-Type` does not declare a specific encoding.

Currently this library invokes that functionality not only on text responses (the ones with an actual character encoding) but also _binary_ responses (which won't have a meaningful character encoding) -- e.g. when downloading an issue attachment.

I've posted this as a pr -- #104 -- and have replied to your objections, but am quite afraid that without an actual open ticket to track, this issue will become lost.
##

**Comment by mrts** [comment]
+1. There is no downside in using `content` instead of `text` as in pull request #104. `content` is just unencoded binary response content, see [requests docs](http://docs.python-requests.org/en/latest/user/quickstart/#binary-response-content). It has nothing to do with W3C standards and works well in Py3 as well.

**Comment by joshfriend** [comment]
This is fixed as of v1.0.3
