### ISSUE TITLE
Usage of `pkg_resources` slows down imports

### ISSUE THREAD

**Issue by vkomarov-r7** [pycontribs/jira#1248]
### Bug summary

The project uses `pkg_resources` for setting version information:

https://github.com/pycontribs/jira/blob/main/jira/__init__.py#L2-L7

If possible, this should be removed in favor of importlib or static `version.py` generation.

Refs:

* https://github.com/pypa/setuptools/issues/510
* https://github.com/protocolbuffers/protobuf/issues/7393

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Jira Instance type

Jira Cloud (Hosted by Atlassian)

### Jira instance version

any

### jira-python version

main

### Python Interpreter version

any

### Which operating systems have you used?

- [X] Linux
- [X] macOS
- [X] Windows

### Reproduction steps

```python
# Run: `python -c "import jira"`
# Observe `pkg_resources` taking a long time to import for larger projects.
```

### Stack trace

```python
N/A
```

### Expected behaviour

I expect `pkg_resources` to not be used so that the startup time is reasonable.

**Comment by 3V3RYONE** [comment]
Hey! I would like to work on this issue. May I? :)

**Comment by 3V3RYONE** [comment]
Hello @vkomarov-r7  @adehad , So I tried to work on this issue and these were my observations:  
  
On reviewing other python modules like pip, they explicitly mention their version in their **```__init__.py```** file, instead of using package distributions (like pkg_resources) to determine the current version. This ensures that importing the package/module is very faster and efficient.  
  
Following are some links to support my point :  
1. https://github.com/pypa/pip/blob/main/src/pip/__init__.py#L2-L4  (Link to pip module, how they specify version)
2. https://stackoverflow.com/questions/42810335/python-pkg-resources-get-distribution-alternative  (Link to show how faster this method ```(explicitly specifying)``` is over the ```pkg_resources``` method)

**Comment by adehad** [comment]
Hi @3V3RYONE !

Sorry for the delay, completely happy for you to have a go and for me to review any merge requests.

The recommended solution would be to use [`importlib.metadata.version()`](https://docs.python.org/3/library/importlib.metadata.html#overview), which does not have the same performance penalty, while still giving us the convenience of only worrying about versions in our tags.

This however,is not supported directly in all the python version we support at the moment. So we would need to introduce the backport as a dependency for the older python versions, something like this in our `setup.cfg`:
`importlib_metadata; python_version < 3.8`

Have a look at the docs here:
https://importlib-metadata.readthedocs.io/en/latest/using.html#using


Side Note:
There may be other packages we depend on that use `pkg_resources` still, so this doesn't guarantee everything will be faster, but hopefully a step in the right direction.

**Comment by 3V3RYONE** [comment]
Hey @adehad   
Thank you for your suggestion! I would work on it and let you know the updates :)
