### ISSUE TITLE
Documentation refers to version 1.0.4 but that still remains unreleased

### ISSUE THREAD

**Issue by tomikall** [pycontribs/jira#177]
[The docs](http://jira.readthedocs.org/en/latest/) refer to version 1.0.4 and talk about netrc authentication which is not available in 1.0.3. The latest release available on [PyPi](https://pypi.python.org/pypi/jira/) is 1.0.3.

Selecting the docs for the stable version gives us 0.43 docs.
##

**Comment by dwlocks** [comment]
I have a similar, related confusion:  I believe there is a difference in the versions for wheel packages vs tar.gz source packages.  In an older python installation I got an error from pip that jira==1.0.3 did not exist, and I should choose from a long list of 0.xx packages.  The 0.xx packages match with the git tags for releases.

Why are these different?  Are wheel packages versioned separately because they may contain compiled binary objects?

**Comment by tuukkamustonen** [comment]
Installing directly from master:

    pip install https://github.com/pycontribs/jira/zipball/master

Finds:

    Successfully installed jira-1.0.6

But there's only `1.0.3` in github. A bit confused about what versions actually exist?

**Comment by ssbarnea** [comment]
It may take few more weeks till we will be able to make a new release because there are still broken tests. A new release is impossible without fixing these tests.

**Comment by ssbarnea** [comment]
Version 1.0.7 is now released and also the documentation is now updates.
