### ISSUE TITLE
Version type is not serializable

### ISSUE THREAD

**Issue by cmakara** [pycontribs/jira#186]
If I try to update an issue's fixVersions field I get the following error:
TypeError: <JIRA Version: name=u'2016-03', id=u'12102'> is not JSON serializable
where 2016-03 is the first version in the collection.

The problem can be reproduced as easily as searching for the issue and trying to update its fixversions with the original collection if there is already an element in it.

```
issue = jira.issue('JRA-1330')
issue.update(fixVersions=issue.fields.fixVersions)
```

**Comment by cmakara** [comment]
Could you please provide an update on this issue? Thank you.

**Comment by ssbarnea** [comment]
PRs are welcomed and I would suggest to also write an unit test to replicate it.

Don't forget to make them against develop branch.

**Comment by mattmccormick** [comment]
I had the same issue.  A pull request would probably involve a lot of refactoring because you'd need to provide a new JSON encoder and make changes to the Resource.update method which could potentially break a lot of other calls.

To get around this I just pass in the IDs of the current fixVersions and the new one I want to add:

```
issue = jira.issue('JRA-1330')
versions = [{"id": version.id} for version in issue.fields.fixVersions]
versions.append({"id": *my_new_version_id*})
issue.update(fields=dict(fixVersions=versions))
```
