### ISSUE TITLE
Exception AttributeError: "'NoneType' object has no attribute 'version_info'"

### ISSUE THREAD

**Issue by licorna** [pycontribs/jira#194]
I'm getting this error from this particular line:  https://github.com/pycontribs/jira/blob/develop/jira/client.py#L333. It seems `sys` module is `None` in this context.

Python 2.7.10 (OSX 10.10.5)
Jira:
* 1.0.6.dev20160420173258 (from pip show jira)
* '1.0.6' from `jira.__version__`

**Comment by ssbarnea** [comment]
Yep, you are right about this. That's because how I implemented versioning. Code from `develop` branch will report versions with `0.0.0devTIMESTAMP` format. Code from `master` reports only the version.

The branch information is detected at runtime and for already packed packages the version will not contain the dev part.

We need to look on how others are doing this as I not want to have to modify the SCM to increase the version on development builds. Any kind of help is welcomed!
