### ISSUE TITLE
Search results returning a single duplicate

### ISSUE THREAD

**Issue by ecstar** [pycontribs/jira#197]
When executing search_issues(maxResults=False,fields=......)
over the last 2 days, I've been getting a single duplicate entry on issue_name (basically a primary key conflict on that element), but which item is duplicated varies each time I execute the search, making it remarkably difficult to narrow down what's happening.  Anyone else been seeing this, or am I just losing my mind lol?

**Comment by asqui** [comment]
Interesting. My guess would be that there's a bug in the logic that retrieves batches of issues, causing an overlap. But that's just a wild guess.

How many issues is your query returning? And if you do the same query via the web interface how many issues do you get back?

**Comment by ecstar** [comment]
It returned 24898 in the API call, but 24897 in the web form.  Batching could be an issue, especially with that number; I was wondering if somehow a single issue was modified in the time that the api call returned, and was getting repeated, but that wouldn't quite match the symptoms...

**Comment by asqui** [comment]
Ah okay, that's quite a large number of issues. Batching will be in much smaller groups, so that result set would be coming over as many many separate batches. If there was an overlap on every single batch (per my hypothesis) then we'd expect to see many more duplicates.

Given that we're doing many server queries there's a possibility of racing with edits, as you described. Particularly if the symptoms are transient.

How long does that `search_issues()` call take to return?

**Comment by ecstar** [comment]
Search issues and iterating over the objects returned takes a little over 7 minutes.
Point of order, I can now no longer repro the issue, even though I could do so at-will yesterday, so I'm tempted to chalk this one up to some sort of occasional race condition around edits. I've got a workaround (drop duplicates from the returned results), so I'm immunized either way.

**Comment by ssbarnea** [comment]
Sorry but this is not the right place for dealing with support issues. This has nothing to do with the Python JIRA library, any REST client may encounter the same thing. You should try to use Atlassian forums for this.
