### ISSUE TITLE
maxResults = 50 in search_issues

### ISSUE THREAD

**Issue by rezogot** [pycontribs/jira#20]
Hi,

Just noticed after random update we get only 50 issues max when using the following function in client.py around line 1400:
```python
def search_issues(self, jql_str, startAt=0, maxResults=50, validate_query=True, fields=None, expand=None, json_result=None):
```
so this is always false :

```python
if maxResults is None or not maxResults:
            maxResults = maxi
            infinite = True
```
Changed maxResult in the function's parameters and its okay 
```python
def search_issues(self, jql_str, startAt=0, maxResults=None, validate_query=True, fields=None, expand=None, json_result=None):
```

Hope this helps

**Comment by fabio-silva-movile** [comment]
Hello @rezogot, this is used to control the infinite variable, that can be passed to fetch all result from the jql passed. But the if can be improved, because in python None is interpreted as False. Look at my pull request:

https://github.com/pycontribs/jira/pull/24

**Comment by ssbarnea** [comment]
I included the patch, but the default behaviour remains to return only 50 records. This is by design in order to protect against mistakes, where you could return 100.000 records or more. 

This follows the same model as the other jira APIs. If there will be many others requests a a change here, I will reconsider this.
