### ISSUE TITLE
Migrate tests to use mocking instead of live jira instance instances

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/jira#543]
Currently most tests require a live Jira instance making them very slow and unreliable. 

We should migrate them to use mocks and eliminate the need to access a jira instance. 

Still when doing this we to be careful and use system that can dump expected responses from live Jira so we can update code to work with various versions of Jira. 

It is well known that Jira responses can vary considerably between versions, so we need to be sure that we need to use **versioned-responses**.

Keep in mind that this ticket is huge and that we should implement it gradually, not in one go.

**Comment by hdost** [comment]
@ssbarnea do we want to break this up into some separate tickets? This could be the tracking ticket?
Ticket naming: Mock JIRA <Version> - <TestClass>
Or we could create project Called Mock JIRA.

One question I would have is how are we going to determine what would be the initial test target.
It could be useful to say get a couple of versions that we want to mock towards.

Potentially we just start with Mock JIRA 7.6 and make the changes such that it could support different versions later on. Since this is likely to be a slow burn 7.6 should give us enough time to implement before EOL. Then when we rev, it should not be too much change.
