### ISSUE TITLE
providing a changelog

### ISSUE THREAD

**Issue by RainerHausdorf** [pycontribs/jira#56]
It would be great if you could provide a changelog for the versions of jira. Maybe I just couldn't find it. If thats the case, than sorry for bothering. But maybe you could add a link to it in the documentation or here at git. Thank you.

**Comment by krandell** [comment]
I asked about this here and got no reply:
https://answers.atlassian.com/questions/14210504/where-are-the-release-notes-for-jira-python

**Comment by krandell** [comment]
Just noticed that this has appeared:
https://github.com/pycontribs/jira/blob/877e9b395dc05dc758336eb0b1fc5702a109131c/CHANGELOG
Although it's rather verbose and isn't clearly divided by release.

Oddly there are fewer releases on github than pypi, making it hard to even determine which changesets have gone in since my current version (0.47):
https://github.com/pycontribs/jira/releases
vs.
https://pypi.python.org/simple/jira/

**Comment by ssbarnea** [comment]
The releases on github are newer and added just as a backup for the official ones from pypi. I do not have time to look over them, all I know is that they are supposed to be published by travis after it does publish to pypi.

Regarding better release notes, if you find a better way to generate them I will be more than happy to accept a patch. Now they are fully automated, included releasing a new version if the tests are passing. 

Regarding breaking changes: this should not happen because that's when we will increase major version number. Minor version numbers are for bugfixes and small new features.

Now the only way to be sure that the API would not change is to assure that you are using only code that is covered by the tests. I would be more than happy to accept pull requests for improved tests.
