### ISSUE TITLE
Proposal: Remove Requirement for merging branchs to be up to date.

### ISSUE THREAD

**Issue by hdost** [pycontribs/jira#696]
In general I like the concept of making sure that respective branches are up to date, but I think a better way might be to only allow the rebase and merge option. This should prevent any conflicts from arising, and can allow the flow of development not to be hindered. Since right now any time a change gets pushed through ALL other branches must be rebased and retested.

**Comment by asqui** [comment]
Having tests run on the final code (after any merge or rebase, but before it is committed to master) seems like a good idea, especially given the issues we've had with test stability.

Would "Rebase and Merge" open the possibility of introducing test failures to master due to conflicting interaction between disparate changes (which do not cause a merge conflict, but nonetheless conflict at a conceptual level)?

Given that updating a branch is as simple as clicking a button in the GitHub UI and waiting for the tests to run, it doesn't seem like that much of an overhead. And you don't have to go and do this for *all* open branches after any commit to master -- you just need to do it at some point before a given branch is merged. i.e. during the review/discussion/approval process for the PR.

Perhaps I am missing something?

**Comment by Achimh3011** [comment]
There are only a few people who have merge rights. I would be totally comfortable with leaving it to each of them to make sure the merge succeeds with a green master . That would replace a technically enforced rule to a guideline that can be skipped if the right circumstances are given (e.g., small documentation changes).

However, I would still be in favor of merging/rebasing all non-trivial changes on the PR side.

**Comment by ssbarnea** [comment]
The only way to know if a change does not break anything is to test it before merge in its exact final format. Because GitHub doesn't have a way to do this, the only alternative is to enforce this rule.

Even a trivial documentation change can break something, like publishing the docs, better to keep things safe than being sorry.

If I remember well, rebasing does not lose votes on reviews, so once a PR is reviewed and accepted we can rebase it as last step before merge.

Rebuilding is a small price (delay) to pay for assuring that what we merge is what we tested. Altenative would be to switch to Gerrit and CRs and stop ussing GitHub for PRs.

Please use the +1 (disable rebasing requirement) and -1 (keep rebasing requirement) votes on the ticket in order to express your preference, I am curious how things will evolve in time.
