### ISSUE TITLE
fullname kwarg not honored in jira.add_user

### ISSUE THREAD

**Issue by fender4645** [pycontribs/jira#76]
Note: resubmitting this (originally issue https://github.com/pycontribs/jira/issues/70) but it was closed without explanation.

When using the add_user method to create a new user, one of the keyword arguments is 'fullname'. Regardless of what you put here, the "Full Name" in JIRA is always the username. Example:

```
result = jira.add_user(username='your_mama',
                       email='your_mama@mycompany.com',
                       password="mypassword",
                       fullname="Your Mama",
                       sendEmail=False,
                       active=True
)
```
After running this, when you look on the JIRA instance, the "Full Name" is not set to "Your Mama" but rather 'your_mama'.

Seen with v. jira-0.47

**Comment by geoghegan** [comment]
I am also seeing this issue with jira-0.47. My pull request ( https://github.com/pycontribs/jira/pull/89 ) fixes it for me.

**Comment by geoghegan** [comment]
BTW, looks like commit b03155cf0f936ad1d404acee9fd0bd7ad19347b2 broke a number of things with add_user

**Comment by fender4645** [comment]
Excellent! Thanks, @geoghegan! And thanks for fixing.

**Comment by mccartney** [comment]
I just want to confirm the same problem. 
Apparently, the parameter to the API call was 'fullname', while JIRA calls it 'displayName'.
I haven't tested that in practice, but by reading the code - it looks like geoghegan's fix does the job.

**Comment by geoghegan** [comment]
The API param name of *fullname* doesn't matter - it could be called *foo*, *bar*, or *sausages*. It's assigned correctly to the API call payload later in the code, as `x['displayName'] = fullname`.

The issue is with the **assignment** of the *fullname* variable. When you pass in the *fullname* arg to **add_user()**, it is overwritten inside of the function with the username variable by ` fullname = username`. 

This commit makes the assignment more sane - if the *fullname* arg is not set, it will make the *fullname* (aka the JIRA *displayName* ) the *username*.

I am hoping @ssbarnea or another commiter will commit this change to mainline in the not too distant future, as it's basic functionality that is broken

**Comment by geoghegan** [comment]
The commit has been merged into mainline! I don't know if I can close this issue, but to me it's resolved.

**Comment by fender4645** [comment]
Thanks @geoghegan. I'll close.
