### ISSUE TITLE
JIRA response still not picklable

### ISSUE THREAD

**Issue by charlesoblack** [pycontribs/jira#790]
**Describe the bug**
Using `pickle.dump` followed by `pickle.load` causes a `RecursionError` to be thrown, even on the `master` development branch.

**To Reproduce**
```
jira_instance = jira.JIRA(jira_link, basic_auth=auth_tuple)
tickets = jira_instance.search_issues('updated >= -1d')
with open('test-jira-pickle.pckl', 'wb') as f:
    pickle.dump(tickets,f)
with open('test-jira-pickle.pckl', 'rb') as f:
    pickle.load(f)  # recursion
```

This seems to be because 1. `self[item]` is used in `resources.py` Resource object 2. `hasattr` is used inside `__getattr__` which is the function that python calls when `hasattr` is used.

**Expected behavior**
JIRA response gets pickled properly and loads properly.

**Stack Trace**
```
File "c:\python37\lib\site-packages\jira\resources.py", line 188 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
...
```

**Version Information**
Python Interpreter: 3.7.0
jira-python: 2.0.1.0rc3.dev2
OS: Windows Server 2016
IPython (Optional): N/A
Other Dependencies:

**Additional context**
N/A

**Comment by charlesoblack** [comment]
@ssbarnea I'd appreciate a quick reply if you have time. I can explore around if you give me suggestions, and report back.

**Comment by rustyscottweber** [comment]
I just ran into the same problem.  What I'm running into is that many of the Jira classes are missing a `__dict__` method which python is going to use to attempt to serialize all of the objects.  If the method exists, it will attempt to serialize data which cannot be serialized.  This includes sockets and weakrefs. Any `__dict__` method should strip these values out entirely or replace them with a string.  A weakref to an object higher up in the structure will create a loop which is why you get your recursion error. If I get a work around, I'll do my best to post it here, but a solution needs to be made by the curators.

**Comment by ssbarnea** [comment]
I personally fail to see how a HTTP session would be serializable but if someone adds required methods and *tests*, I would review them.

**Comment by charlesoblack** [comment]
Personally, I don't care for the HTTP session itself. What I care about are tickets I pull with `search_issues`. I don't see why these *shouldn't* be serializable - all the information should already be downloaded off the API and in memory, unless I'm misunderstanding how this package works.

**Comment by rustyscottweber** [comment]
I agree, I don't think anyone cares about serializing the session, they just want to save the data out to a file.

**Comment by JasonKempSEL** [comment]
Is there a reason you wouldn't just write the files out as JSON? Issue objects are easy to "manually" recreate with the JSON contents.

**Comment by charlesoblack** [comment]
That's not a solution, it's a workaround. `__getattr__()` shouldn't be calling itself in the first place :)

**Comment by ssbarnea** [comment]
Lots of reasons for returning objects intead of JSON. Those that really want JSON could easily talk with JIRA REST API directly. This libary is older than the REST API in JIRA and its functions allow for easy interactions with jira that would not be possible directly.

So, please make PR to address the recursivity issues and also add an unit test for pickle, so we would avoid regressions. That is not the first time when picking got broken.

If I remember whell the search issue returns an interator and while you parse it it may make other requests to jira to load additional result pages. You should try to convert it to a list first, just to be sure.

**Comment by crazySocket** [comment]
I would highly appreciate that feature. The workaround I am using right now is

```python
def load_state(file):
    dumpster = pickle.load(file)
    for dump in dumpster:
        issues.append(Issue(jira._options, jira._session, dump))

def save_state(file):
    dumpster = []
    for issue in issues:
        dumpster.append(issue.raw)
    pickle.dump(dumpster, file)
```

I need to go through changelog a lot. Since jira is just a tool for me (not the main focus) I would like to delegate parsing json to your library instead doing it myself. But passing _session to Issue keeps data and behaviour tighly coupled.

Probably I will be forced to feed issue a fake session because my jira happens to be down from time to time. And then my tool is useless to my users. Thus I strongly advocate for `pickle` support.

**Comment by charlesoblack** [comment]
Could we maybe make this issue not closeable by the bot? @ssbarnea

**Comment by ssbarnea** [comment]
@charlesoblack No really. If nobody is fixing it and nobody refresh it every 3 months it will endup being closed. No need to worry about closed status, you can still comment on them.

What I would probably change is to rename wontfix label to stale, to avoid confusing people as the real meaning of this label is "nobody worked on it for very long time, it is never expected to be fixed". Is not really that "we don't want it fixed". 

I am fully aware about picking issue, but is sensitive issue and I am not sure if there is a way to address it: what fields define an issue? An issue is linked to other objects that can change at any time, what you loaded 5 minutes ago may be outdated by now if someone else edited it, added a comment, modified a version,.... 

Also a ticket picked by an user may not be accessible to another user that may try to load it.

To sort this we should look at what other python libraries did, maybe we can find a working example on a popular project.

**Comment by crazySocket** [comment]
My case is I need to store the data for long enough time to generate a report. This is somewhat iterative process. Add a label to a plot. Change color. Generate csv. Things like that. But to force a user to download entire dataset each time, each download takes 10 min, is unfeasible. Obviously ever greedy users ask me already about 'git-like' update to the downloaded dataset but as far as I know it is perfectly acceptable to redownload entire dataset once a day. Not every 5 min when one applies final tunes to a report.

**Comment by englel-hpe** [comment]
How about for testing? Writing unit tests isn't exactly possible without an object we can reproduce. In the case of testing, I don't care what state the issue is in in jira at the time my tests are running; I just want an object I can reproduce to be identical every time. I'll be using @crazySocket's workaround in the meantime, but having a pickleable object would be nice in this instance.

I think if someone decides to pickle an object, they should know it could be out of sync by the time they decide to use it. If that messes them up it's on them for not understanding how pickling works.

**Comment by brandon-sling** [comment]
With pickling not working even with `__getattr__` overwritten what about just removing it? It seems to conflict with the ability to use the `@property` descriptor in sub-classes.
```
class Foo(Issue):
  def __init__(self, issue):
    super().__init__(issue._options, issue._session, issue.raw)
  @property
  def foo_prop(self):
    return self.fields.customfield_12345.value

class Bar(Foo):
  def __init__(self, issue):
    super().__init__(issue)

bar = Bar(issue)
bar.foo_prop <-- TypeError
python3.7/site-packages/jira/resources.py", line 164, in __getattr__
  return self[item]
TypeError: 'Bar' object is not subscriptable
During handling of the above exception, another exception occurred:
...
python3.7/site-packages/jira/resources.py", line 177, in __getattr__
    raise AttributeError("%r object has no attribute %r (%s)" % (self.__class__, item, e))
AttributeError: <class 'Bar'> object has no attribute 'foo_prop' ('Bar' object is not subscriptable)
```
removing the overwritten dunder method has not caused any issues so far.

**Comment by brandon-sling** [comment]
trying to pickle a list of Issue objects gives `_pickle.PicklingError: Can't pickle <class 'jira.resources.PropertyHolder'>: attribute lookup PropertyHolder on jira.resources failed` I don't know if this is related to the `__getattr__` override or not
