### ISSUE TITLE
Testing bug TravisCI

### ISSUE THREAD

**Issue by mnadeem-acc** [pycontribs/jira#819]
This is related to PR #813 . I'm trying to get the build to succeed. 
The build seems to fail at authenticating. I was wondering if there was some token I had to change within the unit tests to fix this

**Comment by ssbarnea** [comment]
There is a huge list of changes that is needed in order to fix CI. I worked on it last weekend and failed to finish. I will have another attempt next one.

Mainly Atlassian broke lots of APIs and their create project enpoints report 500 errors without details. I was in contact with their support team but I do not have a fix yet. Mainly no project can be created on the integration cloud instance --- which means no tests will pass.
