### ISSUE TITLE
Please tell me why there are some items that cannot be updated

### ISSUE THREAD

**Issue by cpp-stdio** [pycontribs/jira#857]
**Please tell me why there are some items that cannot be updated**

**program**
```
issue = self._make.getIssue(issueid)
issue.update(datum)

```
**return message**
`Field does not support update 'issuelinks'`

I am developing a tool that can update several items simultaneously but there are some items that cannot be updated as described above. I will something to say about this design.

Because much communication occurs, **the JIRA server and windows PC is very many load.**
In order not to generate useless communication, such meaningless communication should be avoided. That specification makes it difficult situation for me to finish the development of this tool.

I sent a message to change the specification so that it can be updated in one communication.
I sincerely believe that it can be improved.

**Comment by JasonKempSEL** [comment]
Unfortunately, issue links are a different rest endpoint on the Jira side than the issue update endpoint. Because of that, each endpoint must be contacted separately.

**Comment by tsukino-shizuku** [comment]
"Because of that, each endpoint must be contacted separately." even if you say, It is within the same issues for users.

To reduce the waste of communication twice, I proposing to improve.
I said it before. It’s because the JIRA server and the Windows PC are subjected to a lot of very many load.

I think that is what the API should be.
