### ISSUE TITLE
Travis CI is failing *not due* to PR issues

### ISSUE THREAD

**Issue by tubaman** [pycontribs/jira#871]
Travis CI is failing even on a trivial PR: https://github.com/pycontribs/jira/pull/870

**To Reproduce**
1. Create a trivial PR
2. See Travis CI fail

**Expected behavior**
Travis CI should only fail if there are issues with a PR

**Comment by ssbarnea** [comment]
That is true but someone needs to address this, and I am currently not using the library.

PS. By addressing it, I do not mean to disable CI testing, i mean finding a way to make it work. Atlassian test instance is working.

**Comment by tubaman** [comment]
What's the Atlassian test instance?

**Comment by Addono** [comment]
Been looking a bit into this today, the problem is that "Encrypted environmental variables" are used, which are not exposed on PR branches, as you will see when you inspect the build logs for a PR:
```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
```

And indeed, comparing the exposed variables in a PR:
![image](https://user-images.githubusercontent.com/15435678/69344336-85910b80-0c6f-11ea-9167-2cffd63617ef.png)

Versus one by the maintainer:
![image](https://user-images.githubusercontent.com/15435678/69344406-a22d4380-0c6f-11ea-8ff7-ba4b59a217d7.png)


Solution wise, Travis' [documentation](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) states this:
> If your build relies on encrypted variables to run, for instance to run Selenium tests with BrowserStack or Sauce Labs, your build needs to take this into account. You won’t be able to run these tests for pull requests from external contributors.
>
> To work around this, **restrict these tests only to situations where the environment variables are available, or disable them for pull requests entirely,** as shown in the following example:
> ...

An alternative solution would be to see if we can for example spin up a JIRA test instance as part of the CI/CD, then use that for testing, and afterwards tear it down. I am currently doing something like that in a Jenkins pipeline, which works fine, although it does take a minute or so for JIRA server to boot. But given that the current Travis pipeline already takes a couple of minutes this shouldn't be too much of an issue.

What could also work would be to make the CI user credentials public. Given that the Jira instance is solely used for testing is there not much damage one can do with these accounts (e.g. delete projects), although that would only be an option if it can be configured such that it has enough rights to pass the tests, but not enough to escalate its rights. For which I do not know if this is feasible.

**Comment by Addono** [comment]
> What's the Atlassian test instance?
[https://pycontribs.atlassian.net/](
https://pycontribs.atlassian.net/)

**Comment by ssbarnea** [comment]
See https://github.com/pycontribs/jira/issues/896
