### ISSUE TITLE
Any plan for the official 3.0 release ?

### ISSUE THREAD

**Issue by Djailla** [pycontribs/jira#967]
I can only see beta on PyPi ?

**Comment by osuchw** [comment]
You could try installing it directly from GitHub.
`pip install -U git+https://github.com/pycontribs/jira.git@3.0`

**Comment by Djailla** [comment]
This is not suitable for production applications :(

**Comment by RedneckEdamame** [comment]
Are there blockers to releasing 3.0 to PyPi? I'm happy to chip in to help package it.

**Comment by studioj** [comment]
@RedneckEdamame have a look here if you want to contribute https://github.com/pycontribs/jira/issues/896

**Comment by studioj** [comment]
@adehad @Addono @ssbarnea can we make a Todo list of what needs to be done for another pypi release?
Maybe @RedneckEdamame @vpolimenov @jpyams @Djailla @osuchw could help out with some beta testing?

**Comment by vpolimenov** [comment]
@studioj yeah I would be happy to

**Comment by adehad** [comment]
Yep sounds like a plan. `tox -e upload` should be all that is required to actually perform the release, perhaps one item for the todo would be an github action that triggers that step manually or otherwise.

If we can get a new milestone for this release (I imagine 4.0.0 as we dropped support for a python version) we can also start tagging any pull requests we want merged in first. I think the key ones are those related to the new GDPR changes. e.g. #927

**Comment by ssbarnea** [comment]
Done 3.0.1 minutes ago. Fixing the release pipeline took far more time than I was hopping.

Those with review rights, please review open PRs, fix them or close them if original OP is not updating them. I also activated discussions, so we can move questions there and cleanup the issue tracker.
